name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main ブランチに push されたときにトリガーされる

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3 # 最新バージョンに変更
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build with Eleventy
        run: npm run build # これで _site フォルダが生成されるはずです

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add _site/*  # _site内のすべてのファイルを追加
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages:gh-pages
        env:
          CI: false
